### ISSUE TITLE
Design issue of client and server packs being the same

### ISSUE THREAD

**Issue by HyperSoop** [modrinth-smp/pack#12]
As far as I know it's still this way, and it should not be.
- Client mods do nothing or bad things on the server
- Server mods are not required on the client
- On either side, those unneeded mods are a tank to perfomance and stability.

**Comment by Gaming32** [comment]
They're separated between sides because of Packwiz and mrpacks. Both keep track of which mods go on the client and server. The autoupdater for the server does in fact have `-s server` to prevent client-side mods from being installed.
