### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by OVAWARE** [modrinth-smp/pack#7]
https://modrinth.com/mod/things
https://modrinth.com/mod/mythicmetals
https://modrinth.com/mod/extended-drawers
https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric
https://modrinth.com/mod/beaconoverhaul
https://modrinth.com/mod/relicex
https://www.curseforge.com/minecraft/mc-mods/gate-of-babylon
https://modrinth.com/mod/immersive-paintings

QOL - Work on clientside but are great for QOL so Id suggest it
---
https://modrinth.com/mod/mouse-tweaks/
https://www.curseforge.com/minecraft/mc-mods/controlling
https://www.curseforge.com/minecraft/mc-mods/origins-extra-keybinds 
https://modrinth.com/mod/dynamiccrosshair
https://modrinth.com/mod/dynamiccrosshaircompat

**Comment by HyperSoop** [comment]
imo random very small content mods are not worth adding; like a few more furniture items or vegetables only complexify stuff for no gameplay gain

**Comment by HyperSoop** [comment]
some of those were added, could this be closed?
